app/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

#from .views import business, stuffs, business_validator, logs, branch, conciliacion, profile, generatereport_sat, downloadreport_sat, profile_options, download_xml_sat, download_manifest_files
from .views import logs, profile, generatereport_sat, downloadreport_sat, profile_options, download_xml_sat, download_manifest_files, download_manifest_pdf, download_manifest_xml

app_name = 'core'

urlpatterns = [
  #url(u'^$', business, name='business'),
  #url(u'^branch/$', branch, name='branch'),
  # url(u'^activate/$', stuffs, name='stuffs'),
  # url(u'^validate/$', business_validator, name='validate'),
  url(u'^logs/$', logs, name='logs'),
  url(u'^generatereport_sat/$', generatereport_sat, name='generatereport_sat'),
  url(u'^downloadreport_sat/(?P<filename>(Reporte_20)[0-9]{2}-[0-1]{1}[0-9]{1}-[0-3]{1}[0-9]{1}_[0-2]{1}[0-9]{1}-[0-5]{1}[0-9]{1}-[0-5]{1}[0-9]{1}[.]csv)/$', downloadreport_sat, name='downloadreport_sat'),
  #url(u'^downloadreport_sat/(?P<filename>(Reporte_20)[0-9]{2}-[0-1]{1}[0-9]{1}-[0-3]{1}[0-9]{1}_[0-2]{1}[0-9]{1}-[0-5]{1}[0-9]{1}-[0-5]{1}[0-9]{1}[.]csv)/$', downloadreport_sat, name='downloadreport_sat'),
  url(u'^profile/options/$', profile_options, name='profile_options'),

  url(r'^download_xml/(?P<uuid>[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})+/$', download_xml_sat, name='download_xml'),
  url(r'^download_manifest_files/$', download_manifest_files, name='download_manifest_files'),

  url(r'^manifest/download/xml/$', download_manifest_xml, name="download_manifest_xml"),
  url(r'^manifest/download/pdf/$', download_manifest_pdf, name="download_manifest_pdf"),
 ]

ublinvoice/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy, re_path
from app.core.accounts import session_verify
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import JavaScriptCatalog
from django.conf import settings
from django.conf.urls.static import static
from pdb import set_trace

from app.users.views import index, index_sat, password_reset

from app.core.accounts import session_verify

from app.core.urls import profile as core_profile
from app.core.views import invoices_sat

from app.invoicing.views import (
    prodservs as invoicing_prodservs,
    receivers as invoicing_receivers,
    new_invoice as invoicing_invoice,
    new_payment as invoicing_payment
)

urlpatterns = [
    url('i18n/', include('django.conf.urls.i18n')),
    url('jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^{}/'.format(settings.ADMIN_URL), admin.site.urls),
    # URLS USERS
    url(r'^', include('app.users.urls')),
    # URLS BUSINESS
    url(r'^business/', include('app.core.urls')),
        url(u'^profile/$', core_profile, name='profile'),

    # URLS FACTURADOR Y OTROS
    url(r'^invoices/', include('app.invoicing.urls')),
        url(r'^Products-Services/', invoicing_prodservs, name='list-prodservs'),
        url(r'^receivers/', invoicing_receivers, name='list-receivers'),
        url(u'^invoicing/$', invoicing_invoice, name='add-invoice'),
        url(u'^invoicing/payments/$', invoicing_payment, name='add-payment'),

    # URLS SOPORTE
    url(r'^support/', include('app.support.urls'),),

    # URL INDEX
    url(r'^$', index, name='index'),

    # URL SAT
    url(r'^sat/$', index_sat, name='index_sat'),
        url(u'^sat/invoices/$', invoices_sat, name='invoices_sat'),
    
    # URL WS
    url(r'^ws/', include('app.cfdi.urls'),),

    # URL CAMBIO DE CONTRASEÑÁ
	url(r'^resetpassword/success/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
	url(r'^account/resetpassword/$', password_reset, name='auth_password_reset'),
    url(r'^app/session/verify/$', session_verify, name='session_verify'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/views.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals

from django.db.models import Q
from django.urls import reverse
from django.db import connection
from django.conf import settings
from django.utils import timezone
from django.shortcuts import render
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.utils.translation import ugettext as _
from django.template.loader import render_to_string
from django.template.response import TemplateResponse
from django.views.decorators.http import require_http_methods
from django.contrib.auth.hashers import check_password, make_password
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import (
  JsonResponse, 
  HttpResponseRedirect, 
  HttpResponse, 
  Http404, 
  HttpResponseForbidden
)

from .models import (
  PasswordHistory, 
  Business, 
  Address, 
  SatFile, 
  Branch, 
  Log, 
  COUNTRY, 
  LOG_ACTIONS,
  FISCAL_REGIME, 
  Manifest,
)
from .decorators import (
  get_query_logs, 
  get_query_branch, 
  get_query_branch_location, 
  get_query_conciliacion, 
  get_query_invoicing_sat, 
  get_report_sat, 
  get_default_business
)
from .catalogs import LOG_MODULES
from .utils.profile import (
  email_validator, 
  imgext_val, 
  validate_csd, 
  validate_pass, 
  datos_series, 
  not_only_numbers
)

from app.users.models import Profile
from app.sat.models.cfdi import CodigoPostal
from app.sat.models.cfdi import RegimenFiscal
from app.users.decorators import has_group, has_groups
from app.invoicing.models import Invoice, InvoicingSerial, Buyer
from app.core.logs import MESSAGES_LOGS

import os
import time
import uuid
import base64
import hashlib
import zipfile
import datetime
import tempfile
from lxml import etree
from unipath import Path
from M2Crypto import EVP
from pdb import set_trace
from M2Crypto import X509
from psycopg2  import sql
from datetime import date
from datetime import datetime
from io import StringIO, BytesIO, TextIOWrapper

import signxml
from helpdesk.models import Queue
from sequences import get_next_value
from sequences.models import Sequence
from signxml import XMLSigner, XMLVerifier
from helpdesk.models import Queue, Ticket, FollowUp, Attachment

from reportlab.lib.units import inch
from reportlab.lib.enums import TA_JUSTIFY
from reportlab.lib.pagesizes import letter, A3, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image


INVOICE_TYPE = {
  'I': '<span class="label label-success">{}</span>'.format(_('Income')),
  'E': '<span class="label label-warning">{}</span>'.format(_('Expenses')),
  'P': '<span class="label label-default">{}</span>'.format(_('Payments')),
  'T': '<span class="label label-danger">{}</span>'.format(_('Transfers')),
  'N': '<span class="label label-info">{}</span>'.format(_('Payroll')),
}

@login_required(login_url='/')
#@get_default_business
def home(request, *args, **kwargs):
  template, context = 'core/home.html', {}
  tab = ''
  role = request.user.profile.role

  if role == 'G' and request.user.has_group('sat'):
    template = 'core/home_sat.html'
  elif role == 'E' and request.user.has_group('staff'):
    return HttpResponseRedirect('/')

  return TemplateResponse(request, template, context)

from django.utils import timezone
@login_required(login_url='/')
@has_groups(['admins','logs'],False)
@get_query_logs
def logs(request, query, *args, **kwargs):
  user = request.user
  template = 'core/logs.html'
  context = {}
  datatable = {
    'data' : [],
    'iTotalRecords': 0,
    'iTotalDisplayRecords': 0,
  }
  log_message = ''
  #set_trace()
  if request.method == 'POST':
    oper = request.POST.get('oper')
    #print ('Que obtiene MESSAGES_LOGS.get() {}'.format(MESSAGES_LOGS))
    log_message = MESSAGES_LOGS.get('mensaje1').get(settings.DEFAULT_LANGUAGE_CODE)
    #log_message = _('Logs were listed')
    Log.objects.log_action(request, '1', 'R', log_message, 'L', '')
    if request.is_ajax() and oper == 'list-logs':
      try:
        start = int(request.POST.get('iDisplayStart'))
        length = int(request.POST.get('iDisplayLength'))
        events_list = []
        logs_append = events_list.append
        logs = Log.objects.filter(query)
        total = logs.count()
        logs = logs[start:start+length]
        for e in logs:
          ip = e.data['ip'] if 'ip' in e.data else ''
          message = e.data['message'] if 'message' in e.data else ''
          info = u'(IP {}) {}'.format(ip, message)
          show_err_exception = (render_to_string('core/strings/log_options.html', {'err_exception':e.err_exception}, request))
          # print(e.user.username, e.action, e.module, info, e.timestamp, show_err_exception)
          logs_append([e.user.username, dict(LOG_ACTIONS)[e.action], LOG_MODULES[e.module], info, e.timestamp, show_err_exception])
        datatable.update({
          'data' : events_list,
          'iTotalRecords': total,
          'iTotalDisplayRecords': total,
        })
        return JsonResponse(datatable)
      except Exception as e:
        print('Events datatable exception {}'.format(e))
        log_message = MESSAGES_LOGS.get('mensaje2').get(settings.DEFAULT_LANGUAGE_CODE)
        #log_message = _('An exception occurred in the Logs view')
        Log.objects.log_action(request, 2, 'R', log_message, 'L', 'Events datatable exception {}'.format(e))
        return JsonResponse(datatable)
      # Log.objects.log_action(request, 5, 'R', "{}".format(message), 'C', '')  
      return JsonResponse(context)
  return TemplateResponse(request, template, context)


@login_required(login_url='/')
def blocked(request):
  return TemplateResponse(request, 'blocked.html')

@login_required(login_url='/')
@has_groups(['clients', 'billings'],False)
def wizard(request, *args, **kwargs):
  context = {}
  template_name = 'wizard/wizard.html'
  user = request.user
  profile = user.profile
  role = profile.role
  is_valid = True
  tax_contract_manifest = request.POST.get('taxpayer_id')
  
  if request.method == 'POST' and request.is_ajax():
    oper = request.POST.get('oper', 'undefined')
    if oper == 'add_bussines':
      # import pdb; pdb.set_trace()
      # set_trace()
      from .utils.wizard import validate_wizard
      # tax_regime = request.POST.get("tax_regime")

      name = request.POST.get("name", '')
      # taxpayer_id = request.POST.get("org_id")

      country = request.POST.get("contry", '')
      # CountrySubentity = request.POST.get('CountrySubentity', '') 
      city = request.POST.get('city', '') 
      stree = request.POST.get('stree', '')
      cp = request.POST.get("cp", '')

      schemeid = request.POST.get("schemeID", '')
      org_id = request.POST.get("org_id", '')
      org_id_party = request.POST.get('org_id_party', '')
      # legal_org_id = request.POST.get('legal_org_id', '')
      # sl_elect_add = request.POST.get("sl_elect_add", '')

      # exter_numb = request.POST.get("exter_numb", '')
      # inter_numb = request.POST.get("inter_numb", '')

      #stree_additional = request.POST.get('stree_additional', None)
      #address_line = request.POST.get('address_line', None)
      # or not CountrySubentity   or not exter_numb or not inter_numb  or not sl_elect_add
      if not country or not stree or not city or not org_id_party:
        return  context.update({"success": False, "message": _("All fields * are required.")})

      # context['taxpayer_id'] = taxpayer_id

      context['taxpayer_id'] = org_id
      account_exists = user.business_set.exists()
      if not account_exists:
        # is_wizard_valid, message = validate_wizard(tax_regime, taxpayer_id, cp)
        # if is_wizard_valid:
        if True: #Verificar lo del regimen fiscal para validarlo
          if not account_exists:
            business = user.business_set.create(
              taxpayer_id= org_id,
            )
          else:
            business = user.business_set.get()

          # business.fiscal_regime =  tax_regime
          business.name = name
          business.organization_id = org_id_party
          # business.legal_organization_id = legal_org_id
          business.schemeid = schemeid
          # business.seller_elect_address = sl_elect_add

          address = Address.objects.create(zipcode=cp)

          # address.street_aditional = stree_additional
          # address.address_line = address_line
          address.country = country
          # address.state = CountrySubentity
          address.city = city
          # address.external_number = exter_numb
          # address.internal_number = inter_numb
          address.street = stree
          address.save()

          business.address = address
          business.save()
          context.update({"success": True, "message": _("Account successfully registered.")})
        else:
          context.update({"success": False, "message": message})
        Log.objects.log_action(request, 5, 'C', MESSAGES_LOGS.get('mensaje3').get(settings.DEFAULT_LANGUAGE_CODE), 'C', '')
      else:
        # set_trace()
        business = user.business_set.get()
        if business.schemeid is None:
          business.schemeid = schemeid
        if not business.organization_id:
          business.organization_id = org_id_party
          # business.legal_schemeid = legal_org_id
        business.save()

        context.update({"success": True, "message": _("Account previously registered.")})
      Log.objects.log_action(request, 5, 'C', MESSAGES_LOGS.get('mensaje4').get(settings.DEFAULT_LANGUAGE_CODE), 'C', '')
    elif oper == 'validate-key-fiel':
      private_key = request.FILES.get('private_key', None)
      if private_key:
        pwd_key = base64.b64decode(request.POST.get('pwd_key'))
        if not pwd_key:
          is_valid = False
          context['message'] = _('Enter the password for the private key.')

app/core/templates/profile/form_csd.html
{% load i18n %}
<div class="col-sm-12" style="padding-bottom: 3rem;">
  <h1 class="text-center"><strong>{% trans 'Certificate management' %}</strong></h1>
  <p class="text-center" style="padding-bottom: 1rem;">{% trans 'At this section you are able to management your certificates.' %}</p>
</div>
<div class="row" style="padding-top: 2rem;">
  <div class="contents hiddem">
    <div class="col-lg-4">
      <span class="text-bold">* {% trans 'Upload private certificate' %}</span>
      <div class="form-group">
        <div class="input-group input-file">
          <span class="input-group-addon btn-choose"><i class="glyphicon glyphicon-paperclip" aria-hidden="true"></i><span style="padding-left: 0.5rem;">{% trans 'Add' %}</span></span>
          <input type="text" class="form-control key" placeholder='{% trans 'Upload private certificate' %}' />
          <span class="input-group-addon btn-reset"><i class="fa fa-trash" aria-hidden="true"></i><span style="padding-left: 0.5rem;">{% trans 'remove' %}</span></span>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <span class="text-bold">* {% trans 'Upload public certificate' %}</span>
      <div class="form-group">
        <div class="input-group input-file">
          <span class="input-group-addon btn-choose"><i class="glyphicon glyphicon-paperclip" aria-hidden="true"></i><span style="padding-left: 0.5rem;">{% trans 'Add' %}</span></span>
          <input type="text" class="form-control cer" placeholder='{% trans 'Upload public certificate' %}' />
          <span class="input-group-addon btn-reset"><i class="fa fa-trash" aria-hidden="true"></i><span style="padding-left: 0.5rem;">{% trans 'Remove' %}</span></span>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <span class="text-bold">* {% trans 'Private key password' %}</span>
      <div class="form-group input-pass">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-key" aria-hidden="true"></i></span>
          <input type="password" class="form-control pass" placeholder='{% trans 'Private key password' %}' />
          <span class="input-group-addon btn-reset"><i class="fa fa-trash" aria-hidden="true"></i><span style="padding-left: 0.5rem;">{% trans 'Remove' %}</span></span>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-12 btns" style="padding-top: 2rem; justify-content: flex-end; display: flex!important;">
    <button class="btn btn-primary new_csd">{% trans 'Add New' %}</button>
    <button class="btn btn-success hiddem add_csd" style="margin-right: 5rem;">{% trans 'Save' %}</button>
    <button class="btn btn-secondary hiddem cancel_csd">{% trans 'Cancel' %}</button>
  </div>
</div>

<table id="dt_csd" class="table table-striped table-bordered nowrap" style="width:100%">
  <thead>
    <tr>
      <th>{% trans 'Status' %}</th>
      <th>{% trans 'Serie' %}</th>
      <th>{% trans 'Emission date' %}</th>
      <th>{% trans 'Expiration date' %}</th>
      <th>{% trans 'Default' %}</th>
    </tr>
  </thead>
</table>

app/core/templates/profile/form_email.html
{% load i18n %}
<style>
  .sorting, .sorting_asc, .sorting_desc {
    background : none;
  }
</style>
<div class="row" style="margin-bottom: 2rem;">
  <div class="col-lg-5 div_add">
    <div class="col-lg-12 "   style="padding-top: 4rem;">
      <span class="text-bold">* {% trans 'New Email' %}</span>
      <div class="input-group div_mail" style="padding-top:0.5rem;">
        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
        <input type="text" class="form-control" name="dest-email"  placeholder="correo electrónico">
        <span class="input-group-addon btn-reset_email"><i class="fa fa-trash" aria-hidden="true"></i><span style="padding-left: 0.5rem;">{% trans 'Remove' %}</span></span>
      </div>
      <small id="email_dom_bussine" class=""></small>
    </div>
    <small id="email_dom_bussine" class=""></small>
    <div class="col-lg-12" style="padding-top: 2rem; justify-content: flex-end; display: flex!important;">
      {% comment %}
      <button class="btn btn-primary new_mails">Nuevo</button>
      <button class="btn btn-danger hiddem cancel_mails" style="margin-left: 2rem;">Cancelar</button>
      {% endcomment %}
      <button class="btn btn-success add_mails">{% trans 'Add' %}</button>
    </div>
  </div>
  <div class="col-md-7" style="padding-top: 0.8rem;">
    <h1 class="text-center"><strong>{% trans 'Mailing list' %}</strong></h1>
    <p style="padding-bottom: 1rem;">{% trans 'At this section you are able to add, edit or delete your email addresses.' %}</p>
    <table id="dt_email" class="table table-striped table-bordered nowrap" style="width:100%">
      <thead>
        <tr>
          <th class="sorting_disabled">{% trans 'Email'%} </th>
          <th>{% trans 'Action' %}</th>
        </tr>
      </thead>
    </table>        
  </div>
</div>

app/core/templates/profile/form_manifest.html
{% load static %}
{% load i18n %}
<div class="row" style="margin-bottom: 2rem;">
	<h1 class="text-center"><strong>{% trans 'Manifest' %}</strong></h1>
	<p class="text-center" style="padding-bottom: 1rem;">{% trans 'At this section you be able to download the signed manifest.' %}</p>
</div>
<div class="row" style="padding-top: 2rem;">
	<div class="col-lg-12" align="center">
		<div class="col-lg-4">
			<br>
			<img src="{% static 'img/xml.png' %}" width="95px" height="90px;"><br><br>
			<a href="{%  url 'core:download_manifest_xml' %}" class="btn btn-block btn-primary btn-download-manifest" act="zip">{% trans 'Download XML file' %}</a>
		</div>
		<div class="col-lg-4">
			<br>
			<img src="{% static 'img/pdf.png' %}" width="90px" height="90px;"><br><br>
			<a href="{%  url 'core:download_manifest_pdf' %}" class="btn btn-block btn-primary btn-download-manifest" act="zip"{% trans 'Download PDF file' %}</a>
		</div>
		<div class="col-lg-4">
			<br>
			<img src="{% static 'img/zip.png' %}" width="90px" height="90px;"><br><br>
			<a href="{%  url 'core:download_manifest_files' %}" class="btn btn-block btn-primary btn-download-manifest" act="zip">{% trans 'Download ZIP file' %}</a>
			<br><br>
		</div>
	</div>
</div>

app/core/templates/profile/form_password.html
{% load i18n %}
<div class="col-lg-12 pass" style="margin-top: 15px">
  <div class="row">
    <div class="col-lg-6">
      <div class="form-group col-lg-12 padd_b">
        <span class="text-bold">* {% trans 'Current password' %}</span>
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-key"></i></span>
          <input type="password" class="form-control" name="last_password" id="last_password" placeholder="{% trans 'Current password' %}" disabled>
        </div>
        <small id="state-help" class=""></small>  
      </div>
      <div class="form-group col-lg-12 padd_b">
        <span class="text-bold">* {% trans 'New password' %}</span>
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-key"></i></span>
          <input type="password" class="form-control" name="new_password" id="new_password" placeholder="{% trans 'New password' %}" disabled>
        </div>
        <small id="state-help" class=""></small>  
      </div>
      <div class="form-group col-lg-12 padd_b confirm">
        <span class="text-bold confirm">* {% trans 'Confirm password' %}</span>
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-key"></i></span>
          <input type="password" class="form-control" name="new_password_confirm" id="new_password_confirm" placeholder="{% trans 'Confirm password' %}" disabled>
        </div>
      </div>
      <div class="col-lg-12 text-right ">
        <button type="button" class="btn btn-primary text-right pass_update"><i class="glyphicon glyphicon-lock" style="padding-right: 0.5rem"></i>{% trans 'Update' %}</button>
        <button type="button" class="btn btn-primary text-right save_pass hiddem" style="margin-right: 2rem"><i class="fa fa-database"></i><span style="padding-left: 0.5rem;">{% trans 'Save' %}</span></button>
        <button type="button" class="btn btn-secondary text-right cancel_pass hiddem"><i class="fa fa-ban"></i><span style="padding-left: 0.5rem;">{% trans 'Cancel' %}</span></button>
      </div>
    </div>
    <div class="col-lg-6 validation">
      <h1 class="text-center" style="padding-bottom: 1rem;"><strong>{% trans 'Your password must have' %}</strong></h1>
      <div class="text-normal">
        <div class="col-sm-6 col-lg-7">
          <h4 class="text-bold">{% trans 'Required' %}:</h4>
          <h5 class="padd_b number">{% trans 'Your password must have a number.' %}</h5>
          <h5 class="padd_b length">{% trans 'Your password must have at least 8 characters.' %}</h5>
          <h5 class="padd_b capital">{% trans 'Your password must have a uppercase letter.' %}</h5>
          <h5 class="padd_b character">{% trans 'Your password must have a special character.' %}</h5>
        </div>
        <div class="col-sm-6 col-lg-5">
          <h5 class="padd_b tiny">{% trans 'Your password must have a lowercase letter.' %}</h5>
          <h5 class="padd_b space">{% trans 'Your password must not have contain any space.' %}</h5>
          <h5 class="padd_b">{% trans 'Your password must be different than previous one.' %}</h5>
        </div>
      </div>
    </div>
  </div>
</div>

app/core/templates/profile/form_serie.html
{% load i18n %}
<div class="row">
  <div class="col-sm-12">
    <h1 class="text-center"><strong>{% trans 'Serie and Folio Management' %}</strong></h1>
    <p class="text-center" style="padding-bottom: 1rem;">{% trans 'At this section you are able to management your series and folios.' %}</p>
  </div>
  <div class="contents_serie hiddem" style="padding-top: 2rem;">
    <div class="col-lg-4">
      <span class="text-bold">* {% trans 'Serie' %}</span>
      <div class="form-group">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-barcode" aria-hidden="true"></i></span>
          <input type="text" class="form-control serie" placeholder="{% trans 'Set the serie' %}" maxlength="25">
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <span class="text-bold">* {% trans 'Folio' %}</span>
      <div class="form-group">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-braille" aria-hidden="true"></i></span>
          <input type="text" maxlength="40" class="form-control folio number" placeholder="{% trans 'Set the folio' %}">
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-12 btns_series" style="padding-top: 2rem; justify-content: flex-end; display: flex!important;">
    <button class="btn btn-primary new_serie">{% trans 'Add' %}</button>
    <button class="btn btn-success hiddem add_serie" style="margin-right: 5rem;">{% trans 'Save' %}</button>
    <button class="btn btn-secondary hiddem cancel_serie">{% trans 'Cancel' %}</button>
  </div>
</div>
<table id="dt_serie" class="table table-striped table-bordered nowrap" style="width:100%">
  <thead>
    <tr>
      <th>{% trans 'Serie' %}</th>
      <th>{% trans 'Folio' %}</th>
      <th>{% trans 'Default' %}</th>
      <th>{% trans 'Action' %}</th>
    </tr>
  </thead>
</table>

app/core/templates/profile/info.html
{% load i18n %}
<div class="row">
  <div class="col-lg-12">
    <ul class="list-group">
      <li class="list-group-item text-muted" contenteditable="false">{% trans 'Profile' %} <i class="fa fa-info-circle"></i></li>
      <li class="list-group-item text-right"><span class="pull-left"><strong class="">{% trans 'Email' %}:</strong></span>
        {% if data.email %}
          {{ data.email }}
        {% else %}
          {% trans 'Not registered' %}
        {% endif %}
      </li>
      <li class="list-group-item text-right"><span class="pull-left"><strong class="">{% trans 'Joined date' %}:</strong></span>
        {% if request.user.date_joined %}
          {{ request.user.date_joined|date:"M d, Y" }}
        {% else %}
          {% trans 'Not registered' %}
        {% endif %}
      </li>
      <li class="list-group-item text-right"><span class="pull-left"><strong class="">{% trans 'Last login' %}:</strong></span>
        {% if request.user.last_login %}
          {{ request.user.last_login|date:"M d, Y" }}
        {% else %}
          {% trans 'Not registered' %}
        {% endif %}
      </li>
    </ul>
  </div>
</div>