app/invoicing/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import (
  # new_invoice, 
  # new_payment,
  stuffs, 
  invoices,
  # prodservs,
  # receivers,
  calculate_amounts,
  download
)

app_name = 'invoicing'

urlpatterns = [

  url(u'^$', invoices, name='list-invoices'),
  url(r'^download_xml/(?P<uuid>[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})+/$', invoices, name='download_xml'),
  url(r'^download_pdf/(?P<uuid>[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})+/$', invoices, name='download_pdf'),

  url(r'download/', download, name='download_file'),

  url(r'^stuffs/$', stuffs, name='get-stuffs'),
  url(r'^calculate/$', calculate_amounts, name='get-amounts'),
]

ublinvoice/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy, re_path
from app.core.accounts import session_verify
from django.utils.translation import ugettext_lazy as _
from django.views.i18n import JavaScriptCatalog
from django.conf import settings
from django.conf.urls.static import static
from pdb import set_trace

from app.users.views import index, index_sat, password_reset

from app.core.accounts import session_verify

from app.core.urls import profile as core_profile
from app.core.views import invoices_sat

from app.invoicing.views import (
    prodservs as invoicing_prodservs,
    receivers as invoicing_receivers,
    new_invoice as invoicing_invoice,
    new_payment as invoicing_payment
)

urlpatterns = [
    url('i18n/', include('django.conf.urls.i18n')),
    url('jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^{}/'.format(settings.ADMIN_URL), admin.site.urls),
    # URLS USERS
    url(r'^', include('app.users.urls')),
    # URLS BUSINESS
    url(r'^business/', include('app.core.urls')),
        url(u'^profile/$', core_profile, name='profile'),

    # URLS FACTURADOR Y OTROS
    url(r'^invoices/', include('app.invoicing.urls')),
        url(r'^Products-Services/', invoicing_prodservs, name='list-prodservs'),
        url(r'^receivers/', invoicing_receivers, name='list-receivers'),
        url(u'^invoicing/$', invoicing_invoice, name='add-invoice'),
        url(u'^invoicing/payments/$', invoicing_payment, name='add-payment'),

    # URLS SOPORTE
    url(r'^support/', include('app.support.urls'),),

    # URL INDEX
    url(r'^$', index, name='index'),

    # URL SAT
    url(r'^sat/$', index_sat, name='index_sat'),
        url(u'^sat/invoices/$', invoices_sat, name='invoices_sat'),
    
    # URL WS
    url(r'^ws/', include('app.cfdi.urls'),),

    # URL CAMBIO DE CONTRASEÑÁ
	url(r'^resetpassword/success/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
	url(r'^account/resetpassword/$', password_reset, name='auth_password_reset'),
    url(r'^app/session/verify/$', session_verify, name='session_verify'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/invoicing/forms/prodserv.py
# -*- coding: UTF-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _

from app.invoicing.models import ProdServ

from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import FormActions
from crispy_forms.layout import Layout, Submit, Div, Button, HTML

class ProdServForm(forms.ModelForm):
    
  class Meta:
    model = ProdServ
    fields = (
      # "prodserv",
      # "key_unit",
      # "identifier",
      # "unit",
      # "unit_price",
      # "description",
      'name',
      'description',
      'unit_code',
      # 'currency_id',
      'list_id',
      'unit_price',
      'origin_country',
      # 'seller_item_identification',
      # 'buyers_item_identification',
      'item_classification_code',
      # 'additional_item_name',
      # 'additional_item_value',
    )
    # error_messages = {
    #   'unit_price':{
    #     'required': (u'Precio unitario es requerido.'),
    #     'max_digits': (u'Asegúrese que el precio unitario no tenga más de %(max)s dígitos.')
    #   },
    #   'prodserv':{
    #     'required': (u'Clave producto servicio es requerido.'),
    #   },
    #   'key_unit':{
    #     'required': (u'Clave unidad es requerido.'),
    #   },
    #   'identifier':{
    #     'required': (u'Identificador es requerido.'),
    #   #'min_length': (u'Identificador debe tener más de %(min)s caracterés.')
    #   },
    #   'unit': {
    #     'required': (u'Unidad es requerida'),
    #   },
    # }

  def __init__(self, *args, **kwargs):
    super(ProdServForm, self).__init__(*args, **kwargs)
    self.helper_prodserv = FormHelper()
    #self.helper_prodserv.wrapper_class = 'form-group'
    # self.helper_prodserv.form_id = 'formProdserv'
    self.helper_prodserv.form_method = 'POST'
    self.helper_prodserv.label_class = 'col-lg-12'
    #self.helper_prodserv.field_class = 'col-lg-8'
    self.helper_prodserv.layout = Layout(
      Div(
        #Div('prodserv', css_class="form-group col-sm-6 col-md-6 col-lg-6 js-example-data-ajax"),
        HTML('''<div class="form-group col-sm-6 col-md-6 col-lg-6">

            <label for="id_prodserv" class="control-label requiredField">Clave Producto/Servicio<strong>*</strong></label>
            <select id="id_prodserv" class="select2-single" name="prodserv" required></select>
          </div>'''
        ),
        #Div('key_unit', css_class="form-group col-sm-6 col-md-6 col-lg-6"),
        HTML('''<div class="form-group col-sm-6 col-md-6 col-lg-6">
            <label for="id_key_unit" class="control-label requiredField">Clave Unidad<strong>*</strong></label>
            <select id="id_key_unit" class="select2-single" name="key_unit" required="required"></select>
          </div>'''
        ),
        Div('listID', css_class="form-group col-sm-6 col-md-6 col-lg-6"),
        Div('unitCode', css_class="form-group col-sm-3 col-md-3 col-lg-3"),
        Div('unitprice', css_class="form-group col-sm-3 col-md-3 col-lg-3"),
        Div('description', css_class="form-group col-sm-12 col-md-12 col-lg-12"),
        Div(
          Submit('addprodserv', 'Agregar'), 
          Button('cancel', 'Cancelar', css_class="canp"), 
          css_class='avoid',
        ),
        css_class='col-sm-12'
      ),
    )

app/invoicing/views.py
# -*- coding: UTF-8 -*-

from django.conf import settings
#from django.db import transaction
from django.db.models import F, Q
from django.core.cache import cache
from django.db import IntegrityError
from django.urls import resolve, reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.template.response import TemplateResponse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseForbidden, HttpResponse
from django.views.decorators.http import require_POST, require_http_methods

from .decorators import get_query_invoicing
from .models import ProdServ, Receiver, Invoice, Buyer

from .utils.cfdi33 import CFDI
from .utils.moneda import numero_a_letras
from .utils.catalogos import PRODSERV, CLAVEUNIDAD
from .utils.pdf import CreatePDF
from app.peppol.utils.utils import CreatePDF as CreatePDF_
from .utils.handler import get_context, post_invoice

#from app.providers.utils.utils import SatValidator
#from app.providers.utils.controller import CreatePDF

from app.sat.tasks import consultar_sat, cancelar_sat

from app.core.models import FISCAL_REGIME, Log, Business
from app.core.catalogs import INVOICE_STATUS
from app.core.decorators import get_default_business, able_to_invoice

from app.sat.models.cfdi import UsoCFDI, ClaveUnidad, ClaveProdServ
from app.sat.models.lco import LRFC

from django.contrib.auth.models import User
from app.sat.models.cfdi import RegimenFiscal 

from app.users.decorators import has_group, has_groups
from app.core.logs import MESSAGES_LOGS

from app.invoicing.forms import (
  InvoiceForm, 
  ProdServForm, 
  ReceiverForm
)

from os import urandom
from pdb import set_trace
from decimal import Decimal
from datetime import datetime
from dateutil.relativedelta import relativedelta
#from celery.task.control import revoke
from ublinvoice.celery import app
from app.core.catalogs import USE_CFDI

import unidecode

from app.sat.utils.connector import SATConnector

from .utils.catalogos import COUNTRY_CODE, UNIT_CODE, CURRENCY_ID, LIST_ID, TAX_CATEGORY_CODE, STANDARD_ITEM_SCHEME
from django.utils.translation import ugettext as _
from app.peppol.models import *
from app.core.models import SatFile

RECEIVER_STATUS = {
  True: '<span class="label label-success">Activo</span>',
  False: '<span class="label label-danger">Suspendido</span>',
}

INVOICE_TYPE = {
  'I': '<span class="label label-success">Ingreso</span>',
  'E': '<span class="label label-warning">Egreso</span>',
  'P': '<span class="label label-default">Pago</span>',
  'T': '<span class="label label-danger">Traslado</span>',
  'N': u'<span class="label label-info">Nómina</span>',
}

def get_celery_status():
  apply_async = False
  try:
    celery_control = app.control
    inspect = celery_control.inspect()
    stats = inspect.stats()
    if stats:
      apply_async = True
  except IOError as e:
    from errno import errorcode
    msg = "Error connecting to the backend: " + str(e)
    if len(e.args) > 0 and errorcode.get(e.args[0]) == 'ECONNREFUSED':
      msg += ' Check that the RabbitMQ/Redis server is running.'
    apply_async = False
  return apply_async and settings.APPLY_ASYNC


@require_http_methods(['GET', 'POST'])
@login_required(login_url='/')
@has_groups(['clients', 'billing'], False)
@get_default_business
# @able_to_invoice
def new_invoice(request, *args, **kwargs):
  template = 'invoicing/new-invoice.html'
  context = {}
  business = kwargs['business']
  certificate = kwargs.get('sat_file', None)
  sat_file = SatFile.objects.filter(business_id=business.id, default=True).last()
  has_certificate = True if sat_file else False
  if request.method == 'POST':
    context = post_invoice(request, business)
    return JsonResponse(
      context
    )
  elif request.method == 'GET':
    context = get_context(request, business, certificate)
  context['has_certificate'] = has_certificate
  print("Context")
  print(context)
  return TemplateResponse(request, template, context) 

@require_http_methods(['GET', 'POST'])
@login_required(login_url='/')
@has_groups(['clients', 'billing'], False)
@get_default_business
@able_to_invoice
def new_payment(request, *args, **kwargs):
  #set_trace()
  template = 'invoicing/new-invoice.html'
  context = {}
  business = kwargs['business']
  certificate = kwargs.get('sat_file', None)
  if request.method == 'POST':
    context = post_invoice(request, business, _type='payment')
    return JsonResponse(context)
  elif request.method == 'GET':
    context = get_context(request, business, certificate, _type='payment')
  return TemplateResponse(request, template, context)


@login_required(login_url='/')
@require_POST
@has_groups(['admins', 'clients', 'billings'], False)
@get_default_business
def stuffs(request, *args, **kwargs):
  from pdb import set_trace
  from app.sat.utils.validate import Catalogos
  from app.cfdi.utils.validate.adicionales import trunc, normal_round
  #set_trace()
  context = {}
  # set_trace()
  oper = request.POST.get('oper')
  prodserv = request.POST.get('prodserv', None)
  keyunit = request.POST.get('keyunit', None)
  identifier = request.POST.get('identifier', None)
  peppolkey = request.POST.get('peppolkey', None)
  quantity = 0.0
  
  if request.POST.get('quantity'):
    quantity = float(request.POST.get('quantity', 1.0))
  amount = Decimal(0.0)
  if request.POST.get('amount'):
    amount = Decimal(request.POST.get('amount', 1.0))
  feeorfee = Decimal(0.0)
  if request.POST.get('feeorfee'):
    feeorfee = Decimal(request.POST.get('feeorfee', 1.0))
  if request.POST.get('discount'):
    discount = Decimal(request.POST.get('discount'))
  try:
    business = kwargs['business']   
    if request.is_ajax():
      if oper == 'get-business-identifier':
        # Error caused in business "Variable declared before assigment"
        query = Q(business=business)
        if prodserv or identifier:
          if prodserv is not None:
            query = query.__and__(Q(item_classification_code__icontains=prodserv))
          elif identifier is not None:
            query = query.__and__(Q(standard_item_identifier__icontains=identifier))      
          context = list(ProdServ.objects.filter(query).values(
            code=F('item_classification_code'), 
            des=F('description'), 
            su=F('unit_code'), 
            iden=F('standard_item_identifier'), 
            price=F('unit_price')
          )[:10])
      elif oper == 'get-amount':
        try:
          amount = 0
          if identifier:
            unit_price = cache.get(identifier)
            prodserv_obj = ProdServ.objects.filter(business=business)
            if unit_price is None:
              if identifier:
                prodserv_obj = prodserv_obj.filter(standard_item_identifier__icontains=identifier).first()
              if prodserv:
                prodserv_obj = prodserv_obj.filter(item_classification_code__icontains=prodserv).first()
              unit_price = prodserv_obj.unit_price
              cache.set(identifier, unit_price)
            amount = trunc((quantity * unit_price), 6, False)
            Log.objects.log_action(request, 5, 'R', u'La cantidad obtenida es: {}'.format(str(amount)), 'I', "")
        except Exception as e:
          print(f'exception {e}')
        context = {'amount': amount}
      elif oper == 'get-receiver':
        taxpayer_id = request.POST.get('taxpayer_id', None)
        if taxpayer_id is not None:
          try:
            #receiver = Receiver.objects.filter(business=business, taxpayer_id__icontains=taxpayer_id, status=True)[:10]          
            receiver = Buyer.objects.filter(business=business, tax_idenfier_number__icontains=taxpayer_id)[:10]          
            context = list(receiver.values('tax_idenfier_number', 'company_name', 'organization_id', 'country'))
          except Exception as e:
            print(str(e))
      elif oper == 'get-prodserv':
        context = []
        if len(prodserv) >= 4:
          for code, description in PRODSERV.items():
            if prodserv is not None and prodserv in code:
              context.append({
                'code': code, 
                'des': '{} - {}'.format(code, description)
              })
        Log.objects.log_action(request, 5, 'R', MESSAGES_LOGS.get('mensaje27').get(settings.DEFAULT_LANGUAGE_CODE).format(str(ProdServ.objects.all().count())), 'I', '')
      elif oper == 'get-keyunit':
        context = []
        if len(keyunit) >= 2:
          for code, description in CLAVEUNIDAD.items():
            if keyunit is not None and keyunit in code:
              context.append({
                'code': code, 
                'des': '{} - {}'.format(code, description)
              })
      elif oper == 'get-tax':
        total_tax = Decimal(0.0)
        #if feeorfee > Decimal(0.0):
        #  total_tax = trunc((amount * feeorfee), 6, False)
        #context = {'total_tax': total_tax}
        # if feeorfee > Decimal(0.0) and discount <= Decimal(0.0):
        #   total_tax = trunc(((feeorfee * amount)/100), 6, False)
        if feeorfee > Decimal(0.0):
          amount_wd = Decimal(trunc((amount-discount), 6, False))
          total_tax = trunc(((feeorfee * amount_wd)/100), 6, False)
          print("amount "+str(amount))
          print("discount "+str(discount))
          print("feeorfee "+str(feeorfee))
          print("amount_wd "+str(amount_wd))
          print("total_tax "+str(total_tax))
        context = {'total_tax': trunc(total_tax, 6, False)}
      elif oper == 'get-country':
        clave = request.POST.get('clave', None)
        from app.sat.models.cfdi import Pais
        countries = Pais.objects.filter(clave__icontains=clave)
        context = list(countries.values('clave', 'descripcion', 'rit'))
      elif oper == 'get-currency':
        from app.sat.models.cfdi import Moneda
        clave = request.POST.get('clave', None)

app/invoicing/templates/invoicing/strings/invoice-options.html
{% load auth_extras %}
{% load i18n %}
{% if status in 'FCRAP'%}
  {% if uuid %}
    <a href="{% url 'invoicing:download_xml' uuid|default:'4A1B43E2-1183-4AD4-A3DE-C2DA787AE56A' %}" class="btn btn-info btn-xs" title="{% trans 'Download XML file' %}"><i class="fa fa-file-excel" aria-hidden="true"></i></a>
    <a href="{% url 'invoicing:download_pdf' uuid|default:'4A1B43E2-1183-4AD4-A3DE-C2DA787AE56A' %}" class="btn btn-warning btn-xs" title="{% trans 'Download PDF file' %}"><i class="fa fa-file-pdf" aria-hidden="true"></i></a>
  {% endif %}
  {# {% if True or request.user|has_group:"emission-cancel" and status not in 'CRA' %} #}
  {% if status not in 'CRAP' and role not in 'A' %}
    <button id="btn-cancel-{{id}}" type="button" class="btn btn-danger btn-xs btn-cancel" data-trigger="manual" data-html="true" data-toggle="popover" data-content="&lt;button type=&quot;button&quot; class=&quot;close&quot; &gt; &times; &lt;/button&gt; &lt;table class=&quot;table table-striped&quot;&gt; &lt;thead&gt; &lt;tr&gt; &lt;th class=&quot;text-nowrap&quot;&gt;{% trans 'Do you want to cancel the invoice?' %}&lt;/th&gt; &lt;/tr&gt; &lt;/thead&gt; &lt;tbody&gt; &lt;tr&gt; &lt;td class=&quot;text-center&quot;&gt; &lt;textarea class=&quot;form-control&quot; id=&quot;notes-{{id}}&quot; aria-describedby=&quot;notesCancel&quot; placeholder=&quot;{% trans 'Add additional notes' %}&quot;&gt; &lt;/textarea&gt; &lt;br&gt; &lt;small id=&quot;notesCancel&quot; class=&quot;form-text text-muted&quot;&gt;{% trans 'Cancellation notes' %}.&lt;/small&gt; &lt;/td&gt; &lt;/tr&gt; &lt;tr&gt; &lt;td class=&quot;text-center&quot;&gt; &lt;button id=&quot;bc-{{id}}&quot; type=&quot;button&quot; data-loading-text=&quot;{% trans 'Canceling...' %}&quot; data-invoice=&quot;{{ id }}&quot; class=&quot;btn btn-danger btn-sm rci&quot; title=&quot;{% trans 'Cancelar invoice' %}&quot;&gt;{% trans 'Yes Cancel' %}&lt;/button&gt; &lt;/td&gt; &lt;/tr&gt; &lt;/tbody&gt; &lt;/table&gt;"><i class="fa fa-times" title="{% trans 'Cancel Invoice' %}" aria-hidden="true"></i></button>
  {# {% elif True or request.user|has_group:"emission-cancel" and status == 'R' %} #}
  {% elif status == 'A' and role not in 'A' %}
    <button type="button" id="btn-stop-cancel-{{id}}" class="btn btn-danger btn-xs" data-html="true" data-toggle="popover" data-content="&lt;table class=&quot;table table-striped&quot;&gt; &lt;thead&gt; &lt;tr&gt; &lt;th class=&quot;text-nowrap&quot;&gt;&amp;iquest;{% trans 'Stop Cancellation?' %}&lt;/th&gt; &lt;/tr&gt; &lt;/thead&gt; &lt;tbody&gt; &lt;tr&gt; &lt;td class=&quot;text-center&quot;&gt; &lt;button type=&quot;button&quot; data-loading-text=&quot;{% trans 'Stopping...' %}&quot; data-invoice=&quot;{{ id }}&quot; class=&quot;btn btn-success btn-sm sci&quot; title=&quot;{% trans 'Stop process' %}&quot;&gt;S&iacute;, {% trans 'Stop' %}&lt;/button&gt; &lt;/td&gt; &lt;/tr&gt; &lt;/tbody&gt; &lt;/table&gt;"><i class="fa fa-ban" title="{% trans 'Stop cancellation' %}" aria-hidden="true"></i></button>
  {% endif %}
  <button type="button" class="btn btn-default btn-xs btn-email-confirm" data-toggle="modal" data-target="#confirm_email" data-invoice="{{ id }}" uuid="{{ uuid }}" title="{% trans 'Send Email' %}"><i class="fa fa-envelope" aria-hidden="true"></i></button>
  {% comment %}
  {% if status not in 'CA' and role not in 'A' %}
    <button data-invoice="{{ id }}" type="button" class="btn btn-default btn-xs usi" data-html="true" data-loading-text="..." data-toggle="popover"><i class="fa fa-retweet" aria-hidden="true" title="{% trans 'Update Status' %}"></i></button>
  {% endif %}
  {% endcomment %}
{% elif status not in 'EFCAP' and role not in 'A' %}
  <button type="button" data-loading-text="..." id="btn-retry-{{id}}" class="btn btn-info btn-xs" data-html="true" data-toggle="popover" data-content="&lt;table class=&quot;table table-striped&quot;&gt; &lt;thead&gt; &lt;tr&gt; &lt;th class=&quot;text-nowrap&quot;&gt;&amp;iquest;{% trans 'Do you want to re-stamp the invoice?' %}&lt;/th&gt; &lt;/tr&gt; &lt;/thead&gt; &lt;tbody&gt; &lt;tr&gt; &lt;td class=&quot;text-center&quot;&gt;&lt;button type=&quot;button&quot; data-loading-text=&quot;{% trans 'Re-stamping...' %}&quot; data-invoice=&quot;{{ id }}&quot; class=&quot;btn btn-success btn-sm rts&quot; title=&quot;{% trans 'Send re-stamped' %}&quot;&gt;S&iacute;, {% trans 'Send' %}&lt;/button&gt;&lt;/td&gt; &lt;/tr&gt; &lt;/tbody&gt; &lt;/table&gt;"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
{% endif %}

app/invoicing/templates/invoicing/strings/invoice-status.html
{% if status == 'F' %}
  <button title="Timbrado" class="btn btn-success btn-xs" ><strong>Timbrado</strong></button>
{% elif status == 'C' %}
  <a href="javascript:;" class="btn btn-danger btn-xs" data-toggle="popover" data-content="{{ error }}"><strong>Cancelado</strong></a>
{% elif status == 'E' %}
  <a href="javascript:;" class="btn btn-danger btn-xs" data-html="true" data-toggle="popover" data-content="{% for message in error_messages.error %}<strong>{{ message.error }}</strong><hr/><ul><li>{{ message.incident }}</li>{% if message.extra_info %}<li>{{ message.extra_info }}</li>{% endif%}</ul>{% endfor %}"><strong>Error</strong></a>
{% elif status == 'A'%}
  <a href="javascript:;" class="btn btn-warning btn-xs" data-html="true" data-toggle="popover" data-content="{% for message in error_messages.error %}<strong>{{ message.error }}</strong><hr/><ul><li>{{ message.incident }}</li>{% if message.extra_info %}<li>{{ message.extra_info }}</li>{% endif%}</ul>{% endfor %}"><strong>Solicitando Cancelación</strong></a>
{% elif status in 'RP'%}
  <a href="javascript:;" class="btn btn-warning btn-xs" data-html="true" data-toggle="popover" data-content="{% for message in error_messages.error %}<strong>{{ message.error }}</strong><hr/><ul><li>{{ message.incident }}</li>{% if message.extra_info %}<li>{{ message.extra_info }}</li>{% endif%}</ul>{% endfor %}"><strong>En Cancelación</strong></a>
{% else %}
  <a href="javascript:;" class="btn btn-info btn-xs" data-html="true" data-toggle="popover" data-content="{% for message in error_messages.error %}<strong>{{ message.error }}</strong><hr/><ul><li>{{ message.incident }}</li>{% if message.extra_info %}<li>{{ message.extra_info }}</li>{% endif%}</ul>{% endfor %}"><strong>Sin Timbrar</strong></a>
{% endif %}

app/invoicing/templates/invoicing/strings/prodserv-label.html
<strong style="cursor: pointer;" title="{{title}}"><small>{{ description }}</small></strong>
{% comment 'test' %}
    <label class="label label-{{ltype}}" title="{{ title }}">{{ description }}</label>
{% endcomment %}

app/invoicing/templates/invoicing/strings/prodserv-options.html
{% comment %}
{% endcomment %}
<button type="button" id="pedit-{{id}}" prodserv="{{id}}" class="btn btn-default btn-xs pe"><i class="fa fa-edit" aria-hidden="true"></i></button>
<!-- <button type="button" prodserv="{{id}}" class="btn btn-default btn-xs ped"><i class="fa fa-edit" aria-hidden="true"></i></button> -->

app/invoicing/templates/invoicing/strings/receiver-emails.html
{% comment %}
{% for email in emails %}
    <span class="label label-emails" title="">{{ email|lower }}</span>
{% endfor %}
{% endcomment %}
<span class="label label-emails" title="">{{ emails|lower }}</span>

app/invoicing/templates/invoicing/strings/receiver-options.html
{% load i18n %}
{% if role not in 'A' %}
	{% comment %}
	{% if receiver.status %}
	    <!--button class="btn btn-success btn-sm sr" title="Activo" receiver="{{ receiver.encrypt }}"><i class="fa fa-check" aria-hidden="true"></i></button-->
	    <button class="btn btn-danger btn-xs sr" title="{% trans 'Suspend' %}" data-receiver="{{ receiver.encrypt }}"><i class="fa fa-ban" aria-hidden="true"></i></button>
	{% else %}
	    <button class="btn btn-success btn-xs sr" title="{% trans 'Active' %}" data-receiver="{{ receiver.encrypt }}"><i class="fa fa-check" aria-hidden="true"></i></button>
	{% endif %}
	{% endcomment %}
{% endif %}
{% comment 'should user be able to delete his/her receivers?' %}
<button class="btn btn-warning btn-xs dr" title="Eliminar Receptor" data-receiver="{{ receiver.encrypt }}"><i class="fa fa-eraser" aria-hidden="true"></i></button>
{% endcomment %}
{% if role in 'ASB' %}
	<button class="btn btn-info btn-xs sdr" title="{% trans 'Business information' %}" data-receiver="{{ receiver.encrypt }}"><i class="fa fa-eye" aria-hidden="true"></i>&nbsp; {% trans 'Business information' %}</button>

{% else %}
	<button class="btn btn-info btn-xs sdr" title="{% trans 'Business information' %}" data-receiver="{{ receiver.encrypt }}"><i class="fa fa-eye" aria-hidden="true"></i></button>
	<button class="btn btn-default btn-xs er" title="{% trans 'Edit business' %}" data-receiver="{{ receiver.encrypt }}"><i class="fa fa-edit" aria-hidden="true"></i></button>
{% endif %}